### ISSUE TITLE
Integration with LifesavingRankings.com

### ISSUE THREAD

**Issue by rubenvanerk** [dennisfabri/JAuswertung#1]
Hi!

I was clicking around in Jauswertung and thought: how cool would it be if LifesavingRankings.com was integrated into this. Couple of things I could think of:

- When adding a `Meldung`, you can choose to search for the equivalent athlete from LifesavingRankings after which the `Meldezeiten` are automatically filled in with the athlete's PR's. Can be edited after this ofcourse. An ID could also be saved to be used in the point below.
- Export option to LifesavingRankings. Competitions can be exported to the LifesavingRankings database with a click on a button. They'll be published after a quick check from my side.

What would you think of this? Would you be willing to work on this with me?

Obviously there are some changes needed on both sides, but I'm also willing to work on Jauswertung itself.

**Comment by dennisfabri** [comment]
Hi Ruben,

for a few years I have been thinking about some extensions around JAuswertung (and also prototyped some technologies). One thing is a database of official times and records (which will be probably two systems). Another one is something like live timings. There are additional things like a registration system etc.

Lets focus on the official times for now. Competitions can be registered and times incl. protocols can be uploaded directly from JAuswertung (the protocols with signatures may be uploaded independently). After a check the times will be published. At this point they could also be transferred to lifesavingrankings.com.  I would also like to implement the synchronization from lifesavingrankins.com back to the other system.

As I talk about systems this does not mean that there runs different software. The focus of the data is different. We need a system that focusses on german athletes/competitions. It therefore may also include smaller competitions with only an impact on a small region. I do not think that you want to include every small competition in lifesavingrankings.com. Furthermore we need to check that some criteria are met to include the competitions in our system.

Having said that, it may be possible to extend the software behind livesavingrankings.com, to fit our needs and to synchronize the two instances in some way or another. As JAuswertung should be able to upload data to our system it is clear that it could also directly upload data to livesavingrankings.com.

Well. This was quite a lot of text and I hope that I made my ideas somewhat clear. I think we are both thinking about the same things with little differences based on our backgrounds. This also means that I would be glad if we can develop something useful together. Basically that is why I started lisasp.org :-)

**Comment by rubenvanerk** [comment]
Thanks for the reply!

About live timings: this is definitely something I have been wanting to implement on LSR because I think it fits the project perfectly. I'd really like to collaborate with this.

About a registration system: believe it or not but that's something I have thought of as well. A system that pulls times from LSR to streamline the sign up process for club managers. Or a system that even lets the athlete do the registration themselves.

Now the last part. If I understand it correctly you've been thinking about creating a database for JAuswertung competitions? Now I feel LSR would be a perfect fit, but I sense you have some concerns:
**1. Results on LSR are not verified and could be wrong.** 
This is absolutely true. This is a problem for the project but it allowed me to collect a huge amount of results. An option to improve the quality of data would be to start marking competitions as `verified` if criteria are met or if the competition was uploaded by JAauswertung for example. Unverified results could be hidden by default or marked as 'unreliable result'.
**2. LSR won't import small German competitions**
> I do not think that you want to include every small competition in lifesavingrankings.com

Yes I do actually!

The mission of LifesavingRankings is to preserve _as many results as possible_. As long as the data looks okay, I want it in the database. This includes the smallest German competitions.  
If the user would like to see results from Germany only, you should just give them the option to do so. [Like this.](https://www.lifesavingrankings.com/top/100m-manikin-carry-with-fins/men/?nationality=84&yob_start=&yob_end=&rangestart=&rangeend=)

If you still think a separate system is the way to go: no problem. Then I'll create an API so you can easily extract the data you need from LSR.

But I think a central system would be the best option for collaboration and for the global lifesaving community. I'm willing to modify LSR greatly to suit your needs.

**Comment by dennisfabri** [comment]
Ok. I think we are heading in the right direction. I will try to come up with some ideas but I will need a bit of time to write them down. I also guess that we should move general the discussion to a different place (e.g. lisasp) and put the change issues to the projects. Does this sound good?
