### ISSUE TITLE
Datei-Öffnen / Speichern-Dialoge crashen (macOS)

### ISSUE THREAD

**Issue by JOKUE2002** [dennisfabri/JAuswertung#14]
Beim Verwenden von JAuswertung unter macOS Sonoma (14.0) hängt sich das Programm beim Öffnen eines Speichern- oder Öffnen-Dialogs auf (not responding).

**Comment by janKossin** [comment]
Ich habe das gleiche Problem. Beim Versuch eine Datei zu öffnen hängt sich das Programm bei mir auf.

**Comment by JOKUE2002** [comment]
Problem besteht weiterhin; 

Ein möglicher Workaround ist, die JAuswertung.app mit Rosetta zu starten (Rechtsklick auf JAuswertung.app > Informationen abrufen > Mit Rosetta öffnen aktivieren)

**Comment by dennisfabri** [comment]
Der Dateidialog wurde mit Version 16.3.0 angepasst, so dass nun eine kompatiblere Version eingesetzt wird.
