### ISSUE TITLE
[Laufliste] Reihenfolge der Disziplinen und Altersklassen nicht mehr berücksichtigt

### ISSUE THREAD

**Issue by MasterCassim** [dennisfabri/JAuswertung#5]
Beim Erstellen einer Laufliste werden die "Reihenfolge der Disziplinen und Altersklassen", die eingegeben wurden nicht mehr berücksichtigt. Stattdessen wird immer die gleichen Reihenfolge generiert.

v16.0.0

**Comment by dennisfabri** [comment]
Ich habe gerade Version 16.0.1 veröffentlicht. Kannst du das Problem bitte noch einmal damit nachstellen?

**Comment by MasterCassim** [comment]
@dennisfabri Das ging flott :) in Version 16.0.1 funktioniert wieder alles wie gewohnt. Dankeschön.
