### ISSUE TITLE
Direkte Kommunikation mit dem ISC bzgl. Liveergebnisse

### ISSUE THREAD

**Issue by joneppie** [dennisfabri/JAuswertung#6]
Will man die Ergebnisse von Meisterschaften als Liveergebnisse direkt auf der Homepage ausgeben wird bisher ein weiteres Programm benötigt (siehe https://atlas.dlrg.de/confluence/display/AN/ISC-Liveergebnisse), dass diese an das ISC der DLRG übertragt. Dieses sollte direkt durch JAuswertung möglich sein.

**Comment by dennisfabri** [comment]
Umgesetzt
